import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

import { getAllCars } from '../lib/api'

export default function Home({ cars }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dream Cars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to My Dream Cars!
        </h1>

        <div className={styles.grid}>
          {cars.map((car)=>
            <Link key={car.slug} href={`/car/${car.slug}`}>
              <h2 className={styles.link}>{car.header}</h2>
            </Link>
          )}
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const cars = (await getAllCars()) ?? []
  return {
    props: { cars },
  }
}
