import ErrorPage from 'next/error'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import {getAllCars, getCarDetailsBySlug} from '../../lib/api'

export default function Car({carDetails}) {
    if ( !carDetails) {
        return <ErrorPage statusCode={404} />
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>{carDetails?.header}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to {carDetails?.header}!
        </h1>
        <p>{carDetails?.content}</p>
      </main>

      <footer className={styles.footer}>
          {carDetails?.footer}
      </footer>
    </div>
  )
}


export async function getStaticProps({ params }) {
    const carDetails = await getCarDetailsBySlug(params.slug)

    return {
        props: {
            carDetails: carDetails ?? null,
        },
    }
}

export async function getStaticPaths() {
    const allCars = await getAllCars()
    return {
        paths: allCars?.map(({ slug }) => `/car/${slug}`) ?? [],
        fallback: true,
    }
}
